Add type declaration files support
byte-fe/gm-crypto pull request #1
Opened 2020-12-16 09:26 UTC by nanlei2000

2020-12-16 09:45 UTC, ArrayZoneYour commented
missing `SM2.constants`

2020-12-16 09:51 UTC, ArrayZoneYour requested changes

2020-12-16 09:51 UTC, ArrayZoneYour commented on types/index.d.ts
> +      inputEncoding?: string;
`string` => `BufferEncoding`

2020-12-16 10:15 UTC, leecade commented
Plz add TS support description in Readme

2020-12-16 13:32 UTC, nanlei2000 commented
@ArrayZoneYour already add the type overloading, review please

2020-12-17 08:51 UTC, ArrayZoneYour approved these changes

2020-12-18 21:07 UTC, merged